# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35f9c0c3cd503b38aadeed97e200859d0c0864677d292ac34f854f87f47eba643fda5c0eb128ac84bc9e521cbb7dfe72f45abfbf64f3ae570ec1d6effb02aeb2

test:
  secret_key_base: ec3b2715083bb16de7277582f1d5bf2a96c136f9fdd7104f97da62693baccef77d9aa6cecea177923303855b393eb5f97700703973a3ed67b58f3c1a1ac89434

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
